### ISSUE TITLE
Color and Sortable Plugin

### ISSUE THREAD

**Issue by nadar** [vavepl/luya-module-portfolio#1]
I just took a very quick look at the screenshots. 

+ For sorting you could use Sortable Plugin with SortableTrait => https://luya.io/api/luya-admin-ngrest-plugins-Sortable
+ For colors (but only supporting hex codes, not RGBa what i saw in your screenshot) => https://luya.io/api/luya-admin-ngrest-plugins-Color

**Comment by vavepl** [comment]
I had to overlook this plugin somewhere: P

the attributes type has been changed

color: https://github.com/vavepl/luya-module-portfolio/commit/a185f73afc04fad9e892e419694a9ac974bf25d9
sortable: https://github.com/vavepl/luya-module-portfolio/commit/16b6f4df2870e450e58c78294855abfd0dc36a4b

**Comment by nadar** [comment]
Don't forget to add the sortable trait to the model and override the field for the sortable index:

```php
public static function sortableField()
{
    return 'priority';
}
```

**Comment by vavepl** [comment]
done https://github.com/vavepl/luya-module-portfolio/commit/4bdd471c78dfc800d93acabd601d084490a4dcbf
