### ISSUE TITLE
togglestatus for active state

### ISSUE THREAD

**Issue by nadar** [vavepl/luya-module-portfolio#2]
Seems like the is_active field is a state toggler. therefore you can use https://luya.io/api/luya-admin-ngrest-plugins-ToggleStatus 

This will allow you to toggle the status of an item even in the crud list.

**Comment by vavepl** [comment]
Thanks for the help, I need to browse through these plugins and documentation :)
https://github.com/vavepl/luya-module-portfolio/commit/322e5904af33564f314a2789776c785045954aa2
