### ISSUE TITLE
Nice preview pictures are gone

### ISSUE THREAD

**Issue by nadar** [vavepl/luya-module-portfolio#7]
The nice preview pictures in the README.md are gone :-(

**Comment by testt23** [comment]
This user may be not active?

**Comment by nadar** [comment]
@testt23 If you are consuming open source products you should be patient with people, cause in general they are doing this in the spare time!

**Comment by vavepl** [comment]
if I find more time, it will update

**Comment by nadar** [comment]
@vavepl no problem, just saw they where missing on https://luya.io/packages/vavepl--luya-module-portfolio

**Comment by nadar** [comment]
Sadly never fixed.
